export const customers = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "+1 (555) 123-4567",
    totalOrders: 12,
    totalSpent: 1299.99,
    status: "active",
    joinDate: "2023-06-15",
    lastOrder: "2024-01-15",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "+1 (555) 234-5678",
    totalOrders: 8,
    totalSpent: 899.99,
    status: "active",
    joinDate: "2023-08-22",
    lastOrder: "2024-01-12",
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob@example.com",
    phone: "+1 (555) 345-6789",
    totalOrders: 5,
    totalSpent: 449.99,
    status: "inactive",
    joinDate: "2023-09-10",
    lastOrder: "2023-12-20",
  },
  {
    id: 4,
    name: "Alice Brown",
    email: "alice@example.com",
    phone: "+1 (555) 456-7890",
    totalOrders: 15,
    totalSpent: 1899.99,
    status: "active",
    joinDate: "2023-05-03",
    lastOrder: "2024-01-18",
  },
];

export const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    price: 99.99,
    originalPrice: 129.99,
    rating: 4.5,
    reviews: 128,
    image: ["/Image1.jpg", "/Image2.jpg", "/Image3.jpg", "/Image4.jpg"],
    category: "Electronics",
    type: "Audio",
    color: "Black",
    inStock: true,
    discount: 23,
    description:
      "Premium wireless headphones with noise cancellation and 30-hour battery life.",
  },
  {
    id: 2,
    name: "Smart Fitness Watch",
    price: 199.99,
    rating: 4.8,
    reviews: 89,
    image: ["/Image1.jpg", "/Image2.jpg", "/Image3.jpg", "/Image4.jpg"],
    category: "Electronics",
    type: "Wearable",
    color: "Blue",
    inStock: true,
    description: "Advanced fitness tracking with heart rate monitor and GPS.",
  },
  {
    id: 3,
    name: "Organic Cotton T-Shirt",
    price: 29.99,
    rating: 4.2,
    reviews: 45,
    image: ["/Image1.jpg", "/Image2.jpg", "/Image3.jpg", "/Image4.jpg"],
    category: "Clothing",
    type: "Apparel",
    color: "White",
    inStock: false,
    description: "Comfortable organic cotton t-shirt in various colors.",
  },
  {
    id: 4,
    name: "Laptop Stand Adjustable",
    price: 49.99,
    rating: 4.6,
    reviews: 67,
    image: ["/Image1.jpg", "/Image2.jpg", "/Image3.jpg", "/Image4.jpg"],
    category: "Accessories",
    type: "Office",
    color: "Silver",
    inStock: true,
    description: "Ergonomic laptop stand with adjustable height and angle.",
  },
  {
    id: 5,
    name: "USB-C Charging Cable",
    price: 19.99,
    rating: 4.3,
    reviews: 234,
    image: ["/Image1.jpg", "/Image2.jpg", "/Image3.jpg", "/Image4.jpg"],
    category: "Electronics",
    type: "Cable",
    color: "Black",
    inStock: true,
    description: "Fast charging USB-C cable with braided design.",
  },
  {
    id: 6,
    name: "Wireless Mouse",
    price: 39.99,
    rating: 4.4,
    reviews: 156,
    image: ["/Image1.jpg", "/Image2.jpg", "/Image3.jpg", "/Image4.jpg"],
    category: "Electronics",
    type: "Peripheral",
    color: "Gray",
    inStock: true,
    description: "Ergonomic wireless mouse with precision tracking.",
  },
  {
    id: 7,
    name: "Running Shoes",
    price: 89.99,
    rating: 4.7,
    reviews: 203,
    image: ["/Image1.jpg", "/Image2.jpg", "/Image3.jpg", "/Image4.jpg"],
    category: "Clothing",
    type: "Footwear",
    color: "Red",
    inStock: true,
    description: "Comfortable running shoes with excellent cushioning.",
  },
  {
    id: 8,
    name: "Coffee Mug",
    price: 15.99,
    rating: 4.1,
    reviews: 89,
    image: ["/Image1.jpg", "/Image2.jpg", "/Image3.jpg", "/Image4.jpg"],
    category: "Home",
    type: "Kitchenware",
    color: "White",
    inStock: true,
    description: "Ceramic coffee mug with elegant design.",
  },
  {
    id: 9,
    name: "Gaming Keyboard",
    price: 149.99,
    rating: 4.9,
    reviews: 167,
    image: ["/Image1.jpg", "/Image2.jpg", "/Image3.jpg", "/Image4.jpg"],
    category: "Electronics",
    type: "Peripheral",
    color: "RGB",
    inStock: false,
    description: "Mechanical gaming keyboard with RGB backlighting.",
  },
  {
    id: 10,
    name: "Yoga Mat",
    price: 34.99,
    rating: 4.3,
    reviews: 78,
    image: ["/Image1.jpg", "/Image2.jpg", "/Image3.jpg", "/Image4.jpg"],
    category: "Sports",
    type: "Fitness",
    color: "Purple",
    inStock: true,
    description: "Non-slip yoga mat for home workouts.",
  },
];

export const salesData_dashboard = [
  { month: "Jan", sales: 4000, orders: 240 },
  { month: "Feb", sales: 3000, orders: 198 },
  { month: "Mar", sales: 5000, orders: 300 },
  { month: "Apr", sales: 4500, orders: 278 },
  { month: "May", sales: 6000, orders: 389 },
  { month: "Jun", sales: 5500, orders: 349 },
];

export const categoryData_dashboard = [
  { name: "Electronics", value: 35, color: "#8884d8" },
  { name: "Clothing", value: 25, color: "#82ca9d" },
  { name: "Books", value: 20, color: "#ffc658" },
  { name: "Home", value: 20, color: "#ff7300" },
];

export const recentOrders_dashboard = [
  {
    id: "#3210",
    customer: "John Doe",
    amount: 125.5,
    status: "completed",
    time: "2 min ago",
  },
  {
    id: "#3209",
    customer: "Jane Smith",
    amount: 89.99,
    status: "pending",
    time: "5 min ago",
  },
  {
    id: "#3208",
    customer: "Bob Johnson",
    amount: 234.0,
    status: "completed",
    time: "12 min ago",
  },
  {
    id: "#3207",
    customer: "Alice Brown",
    amount: 67.25,
    status: "processing",
    time: "18 min ago",
  },
];

export const topProducts_dashboard = [
  { name: "Wireless Headphones", sales: 234, revenue: 23400, trend: "up" },
  { name: "Smart Watch", sales: 189, revenue: 18900, trend: "up" },
  { name: "Laptop Stand", sales: 156, revenue: 7800, trend: "down" },
  { name: "USB Cable", sales: 145, revenue: 2900, trend: "up" },
];

export const productsDummyData = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    sku: "WBH-001",
    category: "Electronics",
    price: 99.99,
    stock: 45,
    status: "active",
    image: "/placeholder.svg?height=50&width=50",
  },
  {
    id: 2,
    name: "Smart Fitness Watch",
    sku: "SFW-002",
    category: "Electronics",
    price: 199.99,
    stock: 23,
    status: "active",
    image: "/placeholder.svg?height=50&width=50",
  },
  {
    id: 3,
    name: "Organic Cotton T-Shirt",
    sku: "OCT-003",
    category: "Clothing",
    price: 29.99,
    stock: 0,
    status: "out_of_stock",
    image: "/placeholder.svg?height=50&width=50",
  },
  {
    id: 4,
    name: "Laptop Stand Adjustable",
    sku: "LSA-004",
    category: "Accessories",
    price: 49.99,
    stock: 67,
    status: "active",
    image: "/placeholder.svg?height=50&width=50",
  },
  {
    id: 5,
    name: "USB-C Charging Cable",
    sku: "UCC-005",
    category: "Electronics",
    price: 19.99,
    stock: 5,
    status: "low_stock",
    image: "/placeholder.svg?height=50&width=50",
  },
];

export const expenses = [
  {
    id: 1,
    description: "Office Rent",
    amount: 2500.0,
    category: "Rent",
    date: "2024-01-01",
    paymentMethod: "Bank Transfer",
    status: "paid",
    receipt: true,
  },
  {
    id: 2,
    description: "Inventory Purchase - Electronics",
    amount: 15000.0,
    category: "Inventory",
    date: "2024-01-05",
    paymentMethod: "Credit Card",
    status: "paid",
    receipt: true,
  },
  {
    id: 3,
    description: "Marketing Campaign - Google Ads",
    amount: 800.0,
    category: "Marketing",
    date: "2024-01-10",
    paymentMethod: "Credit Card",
    status: "paid",
    receipt: false,
  },
  {
    id: 4,
    description: "Shipping & Logistics",
    amount: 450.0,
    category: "Shipping",
    date: "2024-01-12",
    paymentMethod: "Cash",
    status: "pending",
    receipt: false,
  },
  {
    id: 5,
    description: "Utilities - Electricity",
    amount: 320.0,
    category: "Utilities",
    date: "2024-01-15",
    paymentMethod: "Bank Transfer",
    status: "paid",
    receipt: true,
  },
];

export const categories = [
  "Rent",
  "Inventory",
  "Marketing",
  "Shipping",
  "Utilities",
  "Equipment",
  "Other",
];

export const invoices = [
  {
    id: "INV-001",
    customer: "John Doe",
    email: "john@example.com",
    amount: 299.99,
    status: "paid",
    date: "2024-01-15",
    dueDate: "2024-01-30",
    items: [
      { name: "Wireless Headphones", quantity: 1, price: 99.99 },
      { name: "Smart Watch", quantity: 1, price: 199.99 },
    ],
  },
  {
    id: "INV-002",
    customer: "Jane Smith",
    email: "jane@example.com",
    amount: 149.99,
    status: "pending",
    date: "2024-01-16",
    dueDate: "2024-01-31",
    items: [{ name: "Laptop Stand", quantity: 3, price: 49.99 }],
  },
  {
    id: "INV-003",
    customer: "Bob Johnson",
    email: "bob@example.com",
    amount: 89.99,
    status: "overdue",
    date: "2024-01-10",
    dueDate: "2024-01-25",
    items: [
      { name: "USB Cable", quantity: 2, price: 19.99 },
      { name: "Laptop Stand", quantity: 1, price: 49.99 },
    ],
  },
];

export const productNameOptions = [
  "iPhone 15",
  "Samsung Galaxy S24",
  "MacBook Pro",
  "Dell XPS",
  "Nike Shoes",
  "Adidas T-Shirt",
];
export const categoryOptions = [
  "Saree",
  "Suits",
  "Lungi",
  "Pants",
  "Shirt",
];
export const subcategoryOptions = [
  "South Indian",
  "Banarasi",
  "Surati",
  "Old Ladies",
  "Gorakhpuri",
];
export const colorOptions = [
  "Red",
  "Blue",
  "Green",
  "Black",
  "White",
  "Yellow",
  "Purple",
  "Orange",
  "Pink",
  "Gray",
];
export const productOfOptions = [
  "Anand Synthetics",
  "Ganesh Sytheics",
  "Kashyap Saree center",
  "Laxmi Handloom",
  "Manish Sarees",
  "Raghav Cosmetics",
];

export const tagOptions = [
    "New",
    "Popular",
    "Limited",
    "Exclusive",
    "Premium",
    "Budget",
    "Trending",
  ];