import { staffRoutes } from "@/constants/route.constants.ts/routes.staff";
import { superAdminRoutes } from "@/constants/route.constants.ts/routes.superAdmin";
import { tenantsRoutes } from "@/constants/route.constants.ts/routes.tenants";

export const roleBasedRoutes = {
  superadmin: [
    superAdminRoutes.dashboard,
    superAdminRoutes.activityLogs,
    superAdminRoutes.analytics,
    superAdminRoutes.billing,
    superAdminRoutes.categories,
    superAdminRoutes.chat,
    superAdminRoutes.customerTrends,
    superAdminRoutes.dataManagement,
    superAdminRoutes.emailTemplates,
    superAdminRoutes.featureFlags,
    superAdminRoutes.globalSettings,
    superAdminRoutes.knowledgeBase,
    superAdminRoutes.login,
    superAdminRoutes.logout,
    superAdminRoutes.logs,
    superAdminRoutes.notifications,
    superAdminRoutes.payments,
    superAdminRoutes.plans,
    superAdminRoutes.productAnalytics,
    superAdminRoutes.productPerformance,
    superAdminRoutes.products,
    superAdminRoutes.realTimeChat,
    superAdminRoutes.reports,
    superAdminRoutes.revenueAnalytics,
    superAdminRoutes.roles,
    superAdminRoutes.settings,
    superAdminRoutes.shopAnalytics,
    superAdminRoutes.shopPerformance,
    superAdminRoutes.shops,
    superAdminRoutes.status,
    superAdminRoutes.subscriptions,
    superAdminRoutes.support,
    superAdminRoutes.suspendedUsers,
    superAdminRoutes.system,
    superAdminRoutes.tickets,
    superAdminRoutes.twoFactorAuth,
    superAdminRoutes.userAnalytics,
    superAdminRoutes.users,
  ],
  tenant: [
    tenantsRoutes.dashboard,
    tenantsRoutes.billing,
    tenantsRoutes.customers,
    tenantsRoutes.expenses,
    tenantsRoutes.products,
    tenantsRoutes.settings,
    tenantsRoutes.shop,
    tenantsRoutes.staff,
    tenantsRoutes.invoice,
    tenantsRoutes.reports,
  ],
  staff: [
    staffRoutes.dashboard,
    staffRoutes.attendance,
    staffRoutes.customers,
    staffRoutes.expenses,
    staffRoutes.inventory,
    staffRoutes.notifications,
    staffRoutes.orders,
    staffRoutes.reports,
    staffRoutes.sales,
    staffRoutes.settings,
  ],
};
